project:
  type: website
  output-dir: docs

website:
  title: "Projects"
  description: "My R projects"
  site-url: "https://tylerml71.github.io"
  navbar:
    left:
      - text: "Netflix"
        href: netflix.qmd
      - text: "Housing"
        href: housing.qmd
      - text: "NYC Trees"
        href: nytrees.qmd
      - text: "Fact Checking"
        href: facts.qmd
      - text: "Individual Report for Group Project"
        href: individual-report.qmd
    background: primary
    search: false
format:
  html:
    theme: pulse
    toc: false
editor:
  mode: source

